CREATE TABLE cadastrar_aluno(
	nome text not null,
	cidade text,
	bairro text,
	matricula varchar(20) not null,
	curso text not null,
	dataNascimento varchar(11) not null,
	celular varchar(17) not null,
	telefone varchar(17),
	cpf varchar(15),
	rg varchar(20),
	situacao varchar(20) not null,
	email text,
	ne boolean default false,
	nomeResponsavel1 text not null,
	celularResponsavel1 varchar(17) not null,
	telefoneResponsavel1 varchar(17) not null,
	nomeResponsavel2 text,
	celularResponsavel2 varchar(17),
	telefoneResponsavel2 varchar(17),
	informacoesAdicionais text,
	sexo varchar(10) not null,
	uf varchar(2) not null,
	numerocasa varchar(10),
	endereco text,
);