/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.AlunoDAO;
import Modelo.MAluno;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ítalo
 */
public class TCadastrarEditarAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAluno
     */
    Gerenciamento c;
    int tipoCadastrar;
    MAluno alunoEditar;
    DefaultTableModel tabelaAluno;
    boolean jaExecutado = true;

    public void setContole(Gerenciamento g) {
        c = g;
    }

    public void setTipo(int tipoCadastrarOuEditar) {
        tipoCadastrar = tipoCadastrarOuEditar;
    }

    public void setAlunoEditar(MAluno alunoEditar) {
        this.alunoEditar = alunoEditar;
    }

    public void setTabela(DefaultTableModel tabela) {
        tabelaAluno = tabela;
    }

    public TCadastrarEditarAluno() {
        initComponents();
        // 0 cadastrar -- 1 editar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSituacao = new javax.swing.ButtonGroup();
        bgNE = new javax.swing.ButtonGroup();
        jtpTelaDeDados = new javax.swing.JTabbedPane();
        jpDadosPessoais = new javax.swing.JPanel();
        jpDadosDoAluno = new javax.swing.JPanel();
        lblDataDeNascimento = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblUF = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblNE = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfN = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfRG = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jcbUF = new javax.swing.JComboBox<>();
        jcbSexo = new javax.swing.JComboBox<>();
        jftfNascimento = new javax.swing.JFormattedTextField();
        jtfMatricula = new javax.swing.JTextField();
        jcbCurso = new javax.swing.JComboBox<>();
        jcbCursoEmAndamento = new javax.swing.JCheckBox();
        jcbDesistencia = new javax.swing.JCheckBox();
        jcbCursoCompleto = new javax.swing.JCheckBox();
        jcbSim = new javax.swing.JCheckBox();
        jcbNao = new javax.swing.JCheckBox();
        jlbCampoObrigatorio = new javax.swing.JLabel();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jftfCelular = new javax.swing.JFormattedTextField();
        jftfCpf = new javax.swing.JFormattedTextField();
        lblFotoAluno = new javax.swing.JLabel();
        btnAlterarFoto = new javax.swing.JButton();
        jpDadosDoResponsavel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jtfNomeResponsavel1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jftfTelefoneResponsavel1 = new javax.swing.JFormattedTextField();
        jftfCelularResponsavel1 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jtfNomeResponsavel2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jftfTelefoneResponsavel2 = new javax.swing.JFormattedTextField();
        jftfCelularResponsavel2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jpInformacoesAdicionais = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaInformacoesAdicionais = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jlbCadastrar = new javax.swing.JLabel();
        jsSeparador1 = new javax.swing.JToolBar.Separator();
        jlbSalvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtpTelaDeDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtpTelaDeDados.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jtpTelaDeDados.setToolTipText("");
        jtpTelaDeDados.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N

        jpDadosPessoais.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jpDadosDoAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDataDeNascimento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataDeNascimento.setText("Nascimento:*");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNome.setText("Nome:*");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEndereco.setText("Endereço:");

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCidade.setText("Cidade:");

        lblMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMatricula.setText("Matrícula:*");

        lblSituacao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSituacao.setText("Situação:*");

        lblNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNo.setText("Nº:");
        lblNo.setToolTipText("");

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBairro.setText("Bairro:");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCPF.setText("CPF:");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCelular.setText("Celular:*");

        lblRG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRG.setText("RG:");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmail.setText("Email:");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCurso.setText("Curso:*");

        lblUF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUF.setText("UF:*");

        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSexo.setText("Sexo:*");

        lblNE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNE.setText("Possui alguma necessidade especial?*");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.setToolTipText("");
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jtfEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jtfN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNKeyTyped(evt);
            }
        });

        jtfBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBairroActionPerformed(evt);
            }
        });

        jtfRG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRGKeyTyped(evt);
            }
        });

        jtfCidade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyTyped(evt);
            }
        });

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jcbUF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "------------", "Ac", "Al", "Ap", "Am", "Ba", "Ce", "Df", "Es", "Go", "Ma", "Mt", "Ms", "Mg", "Pa", "Pb", "Pr", "Pe", "Pi", "Rj", "Rn", "Rs", "Ro", "Rr", "Sc", "Sp", "Se", "To" }));

        jcbSexo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "------------", "Masculino", "------------", "Feminino", "------------", "Outro" }));

        try {
            jftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfMatriculaMouseClicked(evt);
            }
        });
        jtfMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMatriculaKeyTyped(evt);
            }
        });

        jcbCurso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o curso:", "----------------------", "IIN-2016", "IIN-2015", "IIN-2014", "IIN-2013", "IIN-2012", "----------------------", "EIN-2016", "EIN-2015", "EIN-2014", "EIN-2013", "----------------------", "TADS", "----------------------", "Ciências Biológicas" }));
        jcbCurso.setToolTipText("");

        bgSituacao.add(jcbCursoEmAndamento);
        jcbCursoEmAndamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbCursoEmAndamento.setSelected(true);
        jcbCursoEmAndamento.setText("Curso em Andamento");

        bgSituacao.add(jcbDesistencia);
        jcbDesistencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbDesistencia.setText("Desistência");

        bgSituacao.add(jcbCursoCompleto);
        jcbCursoCompleto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbCursoCompleto.setText("Curso Completo");
        jcbCursoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCursoCompletoActionPerformed(evt);
            }
        });

        bgNE.add(jcbSim);
        jcbSim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbSim.setText("Sim");
        jcbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSimActionPerformed(evt);
            }
        });

        bgNE.add(jcbNao);
        jcbNao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbNao.setSelected(true);
        jcbNao.setText("Não");
        jcbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNaoActionPerformed(evt);
            }
        });

        jlbCampoObrigatorio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jlbCampoObrigatorio.setText("* Campos obrigatórios");

        try {
            jftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpDadosDoAlunoLayout = new javax.swing.GroupLayout(jpDadosDoAluno);
        jpDadosDoAluno.setLayout(jpDadosDoAlunoLayout);
        jpDadosDoAlunoLayout.setHorizontalGroup(
            jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosDoAlunoLayout.createSequentialGroup()
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCelular))
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTelefone))
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosDoAlunoLayout.createSequentialGroup()
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEndereco))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addComponent(lblBairro)
                                        .addGap(64, 64, 64)))
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfN)
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNo)
                                            .addComponent(lblUF))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosDoAlunoLayout.createSequentialGroup()
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDataDeNascimento)
                                            .addComponent(lblCidade))
                                        .addGap(42, 42, 42)
                                        .addComponent(lblRG)
                                        .addGap(11, 11, 11))
                                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addComponent(jtfMatricula)
                                        .addGap(16, 16, 16))
                                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMatricula)
                                            .addComponent(lblSituacao)
                                            .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                                .addComponent(jcbSim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcbNao)))
                                        .addGap(83, 83, 83)))
                                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCurso)
                                    .addComponent(jcbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jcbDesistencia)
                            .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                                .addComponent(jcbCursoEmAndamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCursoCompleto))
                            .addComponent(lblNE)
                            .addComponent(jlbCampoObrigatorio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDadosDoAlunoLayout.createSequentialGroup()
                                .addComponent(jftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexo)
                            .addComponent(lblCPF)
                            .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 433, Short.MAX_VALUE))))
        );
        jpDadosDoAlunoLayout.setVerticalGroup(
            jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosDoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCursoEmAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCursoCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDesistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfRG, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDadosDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCampoObrigatorio))
                .addContainerGap())
        );

        lblFotoAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoAluno.setText("Foto do Aluno");
        lblFotoAluno.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()));
        lblFotoAluno.setEnabled(false);

        btnAlterarFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Edit_32x32.png"))); // NOI18N
        btnAlterarFoto.setText("Alterar");
        btnAlterarFoto.setEnabled(false);
        btnAlterarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDadosPessoaisLayout = new javax.swing.GroupLayout(jpDadosPessoais);
        jpDadosPessoais.setLayout(jpDadosPessoaisLayout);
        jpDadosPessoaisLayout.setHorizontalGroup(
            jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                .addGroup(jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnAlterarFoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDadosDoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDadosPessoaisLayout.setVerticalGroup(
            jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                .addGroup(jpDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarFoto))
                    .addComponent(jpDadosDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpTelaDeDados.addTab("Dados Pessoais", new javax.swing.ImageIcon(getClass().getResource("/Icone/user/user_Add32x32.png")), jpDadosPessoais); // NOI18N

        jpDadosDoResponsavel.setName(""); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Responsável 1", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel33.setText("Nome:*");
        jLabel33.setToolTipText("");

        jtfNomeResponsavel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNomeResponsavel1.setToolTipText("g");
        jtfNomeResponsavel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeResponsavel1KeyTyped(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setText("Celular:*");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setText("Telefone:*");

        try {
            jftfTelefoneResponsavel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfTelefoneResponsavel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfTelefoneResponsavel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jftfCelularResponsavel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCelularResponsavel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCelularResponsavel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfNomeResponsavel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel35)
                                    .addGap(95, 95, 95)
                                    .addComponent(jLabel37)))
                            .addGap(51, 51, 51)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jftfCelularResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jftfTelefoneResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfTelefoneResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfCelularResponsavel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Responsável 2", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel38.setText("Nome:");
        jLabel38.setToolTipText("");

        jtfNomeResponsavel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNomeResponsavel2.setToolTipText("g");
        jtfNomeResponsavel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeResponsavel2KeyTyped(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setText("Celular:");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setText("Telefone:");

        try {
            jftfTelefoneResponsavel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfTelefoneResponsavel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfTelefoneResponsavel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jftfCelularResponsavel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCelularResponsavel2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCelularResponsavel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeResponsavel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel40))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jftfCelularResponsavel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jftfTelefoneResponsavel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeResponsavel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfTelefoneResponsavel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfCelularResponsavel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("* Campos obrigatórios");

        javax.swing.GroupLayout jpDadosDoResponsavelLayout = new javax.swing.GroupLayout(jpDadosDoResponsavel);
        jpDadosDoResponsavel.setLayout(jpDadosDoResponsavelLayout);
        jpDadosDoResponsavelLayout.setHorizontalGroup(
            jpDadosDoResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosDoResponsavelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosDoResponsavelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jpDadosDoResponsavelLayout.setVerticalGroup(
            jpDadosDoResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosDoResponsavelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosDoResponsavelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jtpTelaDeDados.addTab("Dados do Responsável/Familia", new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User32x32.png")), jpDadosDoResponsavel); // NOI18N

        jpInformacoesAdicionais.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Informações Adicionais:");

        jtaInformacoesAdicionais.setColumns(20);
        jtaInformacoesAdicionais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtaInformacoesAdicionais.setRows(5);
        jScrollPane2.setViewportView(jtaInformacoesAdicionais);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jlbCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/user_Add32x32.png"))); // NOI18N
        jlbCadastrar.setText("Cadastrar");
        jlbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCadastrarMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbCadastrar);
        jToolBar1.add(jsSeparador1);

        jlbSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/user_Add32x32.png"))); // NOI18N
        jlbSalvar.setText("Salvar");
        jlbSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbSalvarMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbSalvar);

        javax.swing.GroupLayout jpInformacoesAdicionaisLayout = new javax.swing.GroupLayout(jpInformacoesAdicionais);
        jpInformacoesAdicionais.setLayout(jpInformacoesAdicionaisLayout);
        jpInformacoesAdicionaisLayout.setHorizontalGroup(
            jpInformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacoesAdicionaisLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpInformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInformacoesAdicionaisLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpInformacoesAdicionaisLayout.setVerticalGroup(
            jpInformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacoesAdicionaisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpInformacoesAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtpTelaDeDados.addTab("Informações Adicionais", new javax.swing.ImageIcon(getClass().getResource("/Icone/Info32x32.png")), jpInformacoesAdicionais); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpTelaDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpTelaDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBairroActionPerformed

    }//GEN-LAST:event_jtfBairroActionPerformed

    private void jcbCursoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCursoCompletoActionPerformed

    }//GEN-LAST:event_jcbCursoCompletoActionPerformed

    private void jcbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNaoActionPerformed

    }//GEN-LAST:event_jcbNaoActionPerformed

    private void jcbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSimActionPerformed

    }//GEN-LAST:event_jcbSimActionPerformed

    private void btnAlterarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFotoActionPerformed

    }//GEN-LAST:event_btnAlterarFotoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        c.vAbrirTelaPrincipal(1, -1);
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // validar letras
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMatriculaKeyTyped
        // validar numeros -- o que estiver dentro das aspas "" não poderá ser digitado no teclado
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfMatriculaKeyTyped

    private void jtfNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNKeyTyped
        // validar numeros
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNKeyTyped

    private void jtfCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyTyped
        // validar letras
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCidadeKeyTyped

    private void jtfRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRGKeyTyped
        // Validar numero
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfRGKeyTyped

    private void jlbCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCadastrarMouseClicked
        // TODO add your handling code here:
        /*String situacao = null;
        String NE = null;
        AlunoDAO alunoDao = new AlunoDAO();
        if (jcbCursoEmAndamento.isSelected()) {
            situacao = jcbCursoEmAndamento.getText();

        } else if (jcbCursoCompleto.isSelected()) {
            situacao = jcbCursoCompleto.getText();

        } else if (jcbDesistencia.isSelected()) {
            situacao = jcbDesistencia.getText();

        }
        if (jcbSim.isSelected()) {
            NE = jcbSim.getText();
        } else if (jcbNao.isSelected()) {
            NE = jcbNao.getText();
        }

        // Verifica se tem campo obrigatório em branco
        if (jtfNome.getText().trim().isEmpty() || jtfMatricula.getText().trim().isEmpty() || jftfNascimento.getText().equals("  /  /    ")
                || jftfCelular.getText().equals("(  ) 9     -    ") || jtfNomeResponsavel1.getText().trim().isEmpty()
                || jftfCelularResponsavel1.getText().equals("(  ) 9     -    ") || jftfTelefoneResponsavel1.getText().equals("(  ) 9     -    ")) {
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");

        } else if (jcbCurso.getSelectedItem().equals("Selecione o curso:")
                || jcbCurso.getSelectedItem().equals("----------------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um curso válido");

        } else if (jcbUF.getSelectedItem().equals("Selecione:")
                || jcbUF.getSelectedItem().equals("------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um estado válido");

        } else if (alunoDao.validarMatriculaExistente(jtfMatricula.getText())) {
            JOptionPane.showMessageDialog(null, "Já existe um aluno com a mesma matrícula no campus");

        } else if (jcbSexo.getSelectedItem().equals("Selecione:")
                || jcbSexo.getSelectedItem().equals("------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um sexo válido");

        } else {
            MAluno aluno = new MAluno(
                    jtfNome.getText(),
                    jtfCidade.getText(),
                    jtfBairro.getText(),
                    jtfMatricula.getText(),
                    jcbCurso.getSelectedItem().toString(),
                    jftfNascimento.getText(),
                    jftfCelular.getText(),
                    jftfTelefone.getText(),
                    jftfCpf.getText(),
                    jtfRG.getText(),
                    situacao,
                    jtfEmail.getText(),
                    NE,
                    jtfNomeResponsavel1.getText(),
                    jftfCelularResponsavel1.getText(),
                    jftfTelefoneResponsavel1.getText(),
                    jtfNomeResponsavel2.getText(),
                    jftfCelularResponsavel2.getText(),
                    jftfTelefoneResponsavel2.getText(),
                    jtaInformacoesAdicionais.getText(),
                    jcbSexo.getSelectedItem().toString(),
                    jcbUF.getSelectedItem().toString(),
                    jtfN.getText(),
                    jtfEndereco.getText()
            );
            c.bCadastrarAluno(aluno);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
            limparCampos();
        }*/
    }//GEN-LAST:event_jlbCadastrarMouseClicked

    private void jlbSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSalvarMouseClicked
        // TODO add your handling code here:
        String situacao = null;
        String NE = null;
        if (jcbCursoEmAndamento.isSelected()) {
            situacao = jcbCursoEmAndamento.getText();
        } else if (jcbCursoCompleto.isSelected()) {
            situacao = jcbCursoCompleto.getText();
        } else if (jcbDesistencia.isSelected()) {
            situacao = jcbDesistencia.getText();
        }
        if (jcbSim.isSelected()) {
            NE = "sim";
        } else if (jcbNao.isSelected()) {
            NE = "nao";
        }
        if (jtfNome.getText().isEmpty() || jtfMatricula.getText().trim().isEmpty() || jftfNascimento.getText().equals("  /  /    ")
                || jftfCelular.getText().equals("(  ) 9     -    ") || jtfNomeResponsavel1.getText().trim().isEmpty()
                || jftfCelularResponsavel1.getText().equals("(  ) 9     -    ") || jftfTelefoneResponsavel1.getText().equals("(  ) 9     -    ")) {
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");

        } else if (jcbCurso.getSelectedItem().equals("Selecione o curso:")
                || jcbCurso.getSelectedItem().equals("----------------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um curso válido");

        } else if (jcbUF.getSelectedItem().equals("Selecione:")
                || jcbUF.getSelectedItem().equals("------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um estado válido");

        } else if (jcbSexo.getSelectedItem().equals("Selecione:")
                || jcbSexo.getSelectedItem().equals("------------")) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um sexo válido");

        } else {/*
            alunoEditar.setNome(jtfNome.getText());
            alunoEditar.setCidade(jtfCidade.getText());
            alunoEditar.setBairro(jtfBairro.getText());
            alunoEditar.setMatricula(jtfMatricula.getText());
            alunoEditar.setCurso(jcbCurso.getSelectedItem().toString());
            alunoEditar.setDataNascimento(jftfNascimento.getText());
            alunoEditar.setCelular(jftfCelular.getText());
            alunoEditar.setTelefone(jftfTelefone.getText());
            alunoEditar.setCpf(jftfCpf.getText());
            alunoEditar.setRg(jtfRG.getText());
            alunoEditar.setSituacao(situacao);
            alunoEditar.setEmail(jtfEmail.getText());
            alunoEditar.setNe(NE);
            alunoEditar.setNomeResponsavel1(jtfNomeResponsavel1.getText());
            alunoEditar.setCelularResponsavel1(jftfCelularResponsavel1.getText());
            alunoEditar.setTelefoneResponsavel1(jftfTelefoneResponsavel1.getText());
            alunoEditar.setNomeResponsavel2(jtfNomeResponsavel2.getText());
            alunoEditar.setCelularResponsavel2(jftfCelularResponsavel2.getText());
            alunoEditar.setTelefoneResponsavel2(jftfTelefoneResponsavel2.getText());
            alunoEditar.setInformacoesAdicionais(jtaInformacoesAdicionais.getText());
            alunoEditar.setSexo(jcbSexo.getSelectedItem().toString());
            alunoEditar.setUf(jcbUF.getSelectedItem().toString());
            alunoEditar.setNumerocasa(jtfN.getText());
            alunoEditar.setEndereco(jtfEndereco.getText());
            c.bEditarAluno(alunoEditar);
            c.vFecharTelaCadastrarEditarAluno(tipoCadastrar);*/
            c.vLimparTabela(tabelaAluno);

        }
    }//GEN-LAST:event_jlbSalvarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        if (tipoCadastrar == 0) {
            jlbSalvar.setVisible(false);
            jsSeparador1.setVisible(false);

        } else if (tipoCadastrar == 1) {
            if (jaExecutado) {
                jaExecutado = false;
                jlbCadastrar.setVisible(false);
                jsSeparador1.setVisible(false);
                jtfMatricula.setEditable(false);

                /*if (alunoEditar != null) {
                    jtfNome.setText(alunoEditar.getNome());
                    jcbCurso.setSelectedItem(alunoEditar.getCurso());
                    jtfEndereco.setText(alunoEditar.getEndereco());
                    jtfN.setText(alunoEditar.getNumerocasa());
                    jtfCidade.setText(alunoEditar.getCidade());
                    jtfBairro.setText(alunoEditar.getBairro());
                    jcbUF.setSelectedItem(alunoEditar.getUf());
                    jftfNascimento.setText(alunoEditar.getDataNascimento());
                    jtfRG.setText(alunoEditar.getRg());
                    jftfCpf.setText(alunoEditar.getCpf());
                    jftfCelular.setText(alunoEditar.getCelular());
                    jftfTelefone.setText(alunoEditar.getTelefone());
                    jcbSexo.setSelectedItem(alunoEditar.getSexo());
                    jtfEmail.setText(alunoEditar.getEmail());
                    jtfMatricula.setText(alunoEditar.getMatricula());
                    if (alunoEditar.getSituacao().equals(jcbCursoEmAndamento.getText())) {
                        jcbCursoEmAndamento.setSelected(true);

                    } else if (alunoEditar.getSituacao().equals(jcbCursoCompleto.getText())) {
                        jcbCursoCompleto.setSelected(true);

                    } else if (alunoEditar.getSituacao().equals(jcbDesistencia.getText())) {
                        jcbDesistencia.setSelected(true);
                    }
                    if (alunoEditar.getNe().equals("Sim")) {
                        jcbSim.setSelected(true);
                    } else {
                        jcbNao.setSelected(true);
                    }
                    jtfNomeResponsavel1.setText(alunoEditar.getNomeResponsavel1());
                    jftfCelularResponsavel1.setText(alunoEditar.getCelularResponsavel1());
                    jftfTelefoneResponsavel1.setText(alunoEditar.getTelefoneResponsavel1());
                    jtfNomeResponsavel2.setText(alunoEditar.getNomeResponsavel2());
                    jftfCelularResponsavel2.setText(alunoEditar.getCelularResponsavel2());
                    jftfTelefoneResponsavel2.setText(alunoEditar.getTelefoneResponsavel2());
                    jtaInformacoesAdicionais.setText(alunoEditar.getInformacoesAdicionais());
                } else {
                    System.out.println("Não é diferente :/");
                }*/
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jtfMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfMatriculaMouseClicked
        // TODO add your handling code here:
        if (tipoCadastrar == 1) {
            JOptionPane.showMessageDialog(null, "Caso deseja editar a MATRÍCULA será necessário remover esse aluno e inseri-lo novamente");
        }
    }//GEN-LAST:event_jtfMatriculaMouseClicked

    private void jtfNomeResponsavel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeResponsavel1KeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeResponsavel1KeyTyped

    private void jtfNomeResponsavel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeResponsavel2KeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeResponsavel2KeyTyped

    public void limparCampos() {
        jtfNome.setText("");
        jcbCurso.setSelectedIndex(0);
        jtfEndereco.setText("");
        jtfN.setText("");
        jtfCidade.setText("");
        jtfBairro.setText("");
        jcbUF.setSelectedIndex(0);
        jftfNascimento.setText("");
        jtfRG.setText("");
        jftfCpf.setText("");
        jftfCelular.setText("");
        jftfTelefone.setText("");
        jcbSexo.setSelectedIndex(0);
        jtfEmail.setText("");
        jtfMatricula.setText("");
        jcbNao.setSelected(true);
        jcbCursoEmAndamento.setSelected(true);
        jtfNomeResponsavel1.setText("");
        jftfCelularResponsavel1.setText("");
        jftfTelefoneResponsavel1.setText("");
        jtfNomeResponsavel2.setText("");
        jftfCelularResponsavel2.setText("");
        jftfTelefoneResponsavel2.setText("");
        jtaInformacoesAdicionais.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastrarEditarAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCadastrarEditarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNE;
    private javax.swing.ButtonGroup bgSituacao;
    private javax.swing.JButton btnAlterarFoto;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> jcbCurso;
    private javax.swing.JCheckBox jcbCursoCompleto;
    private javax.swing.JCheckBox jcbCursoEmAndamento;
    private javax.swing.JCheckBox jcbDesistencia;
    private javax.swing.JCheckBox jcbNao;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JCheckBox jcbSim;
    private javax.swing.JComboBox<String> jcbUF;
    private javax.swing.JFormattedTextField jftfCelular;
    private javax.swing.JFormattedTextField jftfCelularResponsavel1;
    private javax.swing.JFormattedTextField jftfCelularResponsavel2;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfNascimento;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JFormattedTextField jftfTelefoneResponsavel1;
    private javax.swing.JFormattedTextField jftfTelefoneResponsavel2;
    private javax.swing.JLabel jlbCadastrar;
    private javax.swing.JLabel jlbCampoObrigatorio;
    private javax.swing.JLabel jlbSalvar;
    private javax.swing.JPanel jpDadosDoAluno;
    private javax.swing.JPanel jpDadosDoResponsavel;
    private javax.swing.JPanel jpDadosPessoais;
    private javax.swing.JPanel jpInformacoesAdicionais;
    private javax.swing.JToolBar.Separator jsSeparador1;
    private javax.swing.JTextArea jtaInformacoesAdicionais;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfN;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeResponsavel1;
    private javax.swing.JTextField jtfNomeResponsavel2;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JTabbedPane jtpTelaDeDados;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataDeNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFotoAluno;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNE;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    // End of variables declaration//GEN-END:variables
}
