/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.LoginDAO;
import DAO.NucleoDAO;
import DAO.UsuarioDAO;
import Modelo.MLogin;
import Modelo.MUsuario;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ítalo
 */
public class TCadastrarEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAtendente
     */
    Gerenciamento c;
    int iVeioDeQualTela;
    MUsuario mUsuarioLogado,
            mUsuarioEditado;
    MLogin mLogin;
    UsuarioDAO uDAO;
    LoginDAO lDAO;
    NucleoDAO ndao;
    DefaultTableModel dtmTabelaUsuario;
    boolean bAlterarSiape = false,
            bTeste = true;

    public void setContole(Gerenciamento g) {
        c = g;
    }

    public void setTipo(int tipoCadastrarOuEditar) {
        iVeioDeQualTela = tipoCadastrarOuEditar;
    }

    public void setUsuarioLogado(MUsuario mUsuario) {
        mUsuarioLogado = mUsuario;
    }

    public void setTabela(DefaultTableModel tabela) {
        dtmTabelaUsuario = tabela;
    }

    public TCadastrarEditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jsSeparadorJCB = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        lblFotoAluno = new javax.swing.JLabel();
        btnAlterarFoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfEndereco = new javax.swing.JTextField();
        jtfNumeroDaCasa = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfRG = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jftfCelular = new javax.swing.JFormattedTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jtfEmail = new javax.swing.JTextField();
        jcbUF = new javax.swing.JComboBox<>();
        lblSituacao = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        lblNumeroDaCasa = new javax.swing.JLabel();
        jftfNascimento = new javax.swing.JFormattedTextField();
        lblBairro = new javax.swing.JLabel();
        jtfSiape = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        jcbNucleo = new javax.swing.JComboBox<>();
        lblTelefone = new javax.swing.JLabel();
        jcbAtivo = new javax.swing.JCheckBox();
        lblCelular = new javax.swing.JLabel();
        jcbAusente = new javax.swing.JCheckBox();
        lblRG = new javax.swing.JLabel();
        jcbInativo = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblUF = new javax.swing.JLabel();
        lblDataDeNascimento = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jftfCpf = new javax.swing.JFormattedTextField();
        jlbUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlbSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jcbSenhaVisivel = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaInformacoesAdicionais = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jlbCadastrarOuSalvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFotoAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoAluno.setText("Foto do Atendente");
        lblFotoAluno.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createEtchedBorder()));
        lblFotoAluno.setEnabled(false);

        btnAlterarFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Edit32x32.png"))); // NOI18N
        btnAlterarFoto.setText("Alterar");
        btnAlterarFoto.setEnabled(false);
        btnAlterarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFotoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtfEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfEnderecoKeyTyped(evt);
            }
        });

        jtfNumeroDaCasa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNumeroDaCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroDaCasaActionPerformed(evt);
            }
        });
        jtfNumeroDaCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNumeroDaCasaKeyTyped(evt);
            }
        });

        jtfBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBairroActionPerformed(evt);
            }
        });

        jtfRG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRGKeyTyped(evt);
            }
        });

        jtfCidade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeActionPerformed(evt);
            }
        });
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyTyped(evt);
            }
        });

        try {
            jftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jftfCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfCelularActionPerformed(evt);
            }
        });

        try {
            jftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jftfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfTelefoneActionPerformed(evt);
            }
        });

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jcbUF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "AC", "AL", "AP", "AM", "BA", "CR", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        lblSituacao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSituacao.setText("Situação:*");

        jcbSexo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Masculino", "Feminino", "Outro" }));

        lblNumeroDaCasa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNumeroDaCasa.setText("Nº:");
        lblNumeroDaCasa.setToolTipText("");

        try {
            jftfNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBairro.setText("Bairro:");

        jtfSiape.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfSiape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfSiapeMouseClicked(evt);
            }
        });
        jtfSiape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSiapeActionPerformed(evt);
            }
        });
        jtfSiape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSiapeKeyTyped(evt);
            }
        });

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCPF.setText("CPF:");

        jcbNucleo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbNucleo.setToolTipText("");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTelefone.setText("Telefone:");

        buttonGroup1.add(jcbAtivo);
        jcbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbAtivo.setText("Ativo");

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCelular.setText("Celular:*");

        buttonGroup1.add(jcbAusente);
        jcbAusente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbAusente.setText("Ausente");

        lblRG.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRG.setText("RG:");

        buttonGroup1.add(jcbInativo);
        jcbInativo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbInativo.setText("Inativo");
        jcbInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInativoActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmail.setText("Email:*");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCurso.setText("Núcleo:*");

        lblUF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUF.setText("UF:*");

        lblDataDeNascimento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDataDeNascimento.setText("Nascimento:*");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNome.setText("Nome:*");

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEndereco.setText("Endereço:");

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCidade.setText("Cidade:");

        lblMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMatricula.setText("SIAPE:*");

        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSexo.setText("Sexo:*");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.setToolTipText("");
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("* Campos obrigatórios");

        try {
            jftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbUsuario.setText("Usuário*:");

        jtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });

        jlbSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbSenha.setText("Senha*:");

        jpfSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jcbSenhaVisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSenhaVisivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfBairro)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUF)
                            .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCelular))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfRG)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefone)
                                            .addComponent(lblRG))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCPF)
                                    .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblSexo))))
                    .addComponent(jtfEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroDaCasa)))
                    .addComponent(jtfNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblDataDeNascimento)
                            .addComponent(lblEmail))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfUsuario)
                    .addComponent(jtfSiape)
                    .addComponent(jcbNucleo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpfSenha)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula)
                            .addComponent(lblSituacao)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbInativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbAusente))
                            .addComponent(lblCurso)
                            .addComponent(jlbUsuario))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbSenhaVisivel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbInativo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbAusente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jcbSenhaVisivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnAlterarFoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblFotoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarFoto)
                        .addGap(37, 37, 37))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", new javax.swing.ImageIcon(getClass().getResource("/Icone/user/user_Add32x32.png")), jPanel7); // NOI18N

        jPanel3.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Informações Adicionais:");

        jtaInformacoesAdicionais.setColumns(20);
        jtaInformacoesAdicionais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtaInformacoesAdicionais.setRows(5);
        jScrollPane2.setViewportView(jtaInformacoesAdicionais);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jlbCadastrarOuSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbCadastrarOuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/user_Add32x32.png"))); // NOI18N
        jlbCadastrarOuSalvar.setText("Salvar");
        jlbCadastrarOuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCadastrarOuSalvarMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbCadastrarOuSalvar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informações Adicionais", new javax.swing.ImageIcon(getClass().getResource("/Icone/Info32x32.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFotoActionPerformed
        // asdapsdmaskdmaskdmasdmasçkdmalsaklsldasmldasml
    }//GEN-LAST:event_btnAlterarFotoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (iVeioDeQualTela == 2) {
            c.vAbrirTelaPesquisarUsuario(1);
        } else {
            c.vAbrirTelaPrincipal(6, -1);
        }

    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed

    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jcbInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInativoActionPerformed

    }//GEN-LAST:event_jcbInativoActionPerformed

    private void jtfSiapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiapeKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSiapeKeyTyped

    private void jtfSiapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSiapeActionPerformed

    }//GEN-LAST:event_jtfSiapeActionPerformed

    private void jftfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfTelefoneActionPerformed

    private void jftfCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfCelularActionPerformed

    private void jtfCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCidadeKeyTyped

    private void jtfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeActionPerformed

    }//GEN-LAST:event_jtfCidadeActionPerformed

    private void jtfRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRGKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfRGKeyTyped

    private void jtfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBairroActionPerformed

    }//GEN-LAST:event_jtfBairroActionPerformed

    private void jtfNumeroDaCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroDaCasaKeyTyped
        // TODO add your handling code here:
        String numero = evt.getKeyChar() + "";
        if (c.bIsNumber(numero)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNumeroDaCasaKeyTyped

    private void jtfNumeroDaCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroDaCasaActionPerformed

    }//GEN-LAST:event_jtfNumeroDaCasaActionPerformed

    private void jtfEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEnderecoKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfEnderecoKeyTyped

    private void jlbCadastrarOuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCadastrarOuSalvarMouseClicked
        // TODO add your handling code here:
        /* 0 - tPrincipal -> Usuario -> Cadastrar
         * 1 - tPrincipal -> Gerenciar -> redefinir meus dados (editar)  
         * 2 - tPesquisarUsuario -> Editar
         */
        String situacao = null;
        uDAO = new UsuarioDAO();
        lDAO = new LoginDAO();
        mUsuarioEditado = new MUsuario();
        mLogin = new MLogin();

        if (iVeioDeQualTela == 0) {
            if (jtfNome.getText().trim().isEmpty() || jtfSiape.getText().trim().isEmpty()
                    || jtfUsuario.getText().trim().isEmpty()
                    || jpfSenha.getText().trim().isEmpty()
                    || jtfEmail.getText().trim().isEmpty()
                    || jftfNascimento.getText().equals("  /  /    ")
                    || jftfCelular.getText().equals("(  ) 9     -    ")) {
                JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");

            } else if (jcbNucleo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um núcleo válido");

            } else if (jcbUF.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um estado válido");

            } else if (jcbSexo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um sexo válido");

            } else if (uDAO.bValidarSiapeExistenteDAO(jtfSiape.getText())) {
                JOptionPane.showMessageDialog(null, "Já existe um usuário no sistema com esse mesmo siape, favor informar outro");

            } else if (lDAO.bValidarLoginExistente(jtfUsuario.getText())) {
                JOptionPane.showMessageDialog(null, "Já existe um login no sistema com esse mesmo usuário, favor informar outro");

            } else {
                mUsuarioEditado.setsNome(jtfNome.getText());
                mUsuarioEditado.setsBairro(jtfBairro.getText());
                mUsuarioEditado.setsCelular(jftfCelular.getText());
                mUsuarioEditado.setsCidade(jtfCidade.getText());
                mUsuarioEditado.setsCpf(jftfCpf.getText());
                mUsuarioEditado.setsDataNascimento(jftfNascimento.getText());
                mUsuarioEditado.setsEmail(jtfEmail.getText());
                mUsuarioEditado.setsEndereco(jtfEndereco.getText());
                mUsuarioEditado.setsInformacoesAdicionais(jtaInformacoesAdicionais.getText());
                mUsuarioEditado.setsNucleo(jcbNucleo.getSelectedItem().toString());
                mUsuarioEditado.setsNumeroCasa(jtfNumeroDaCasa.getText());
                mUsuarioEditado.setsRg(jtfRG.getText());
                mUsuarioEditado.setsSexo(jcbSexo.getSelectedItem().toString());
                mUsuarioEditado.setsSituacao(situacao);
                mUsuarioEditado.setsTelefone(jftfTelefone.getText());
                mUsuarioEditado.setsUf(jcbUF.getSelectedItem().toString());
                mUsuarioEditado.setsSiape(jtfSiape.getText());
                mUsuarioEditado.setbUsuarioAtivo(true);
                mLogin.setsSenha(jpfSenha.getText());
                mLogin.setsSiape(jtfSiape.getText());
                mLogin.setsUsuario(jtfUsuario.getText());
                if (lDAO.bValidarLoginExistente(jtfUsuario.getText())) {
                    JOptionPane.showMessageDialog(null, "Já existe um login no sistema com esse mesmo usuário, favor informar outro");
                } else if (uDAO.bCadastrarUsuarioDAO(mUsuarioEditado) && lDAO.bCadastrarLoginDAO(mLogin)) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível cadastrar esse usuário, se o erro persistir consulte o suporte");
                }
            }
        } else {
            if (jcbAtivo.isSelected()) {
                situacao = jcbAtivo.getText();

            } else if (jcbAusente.isSelected()) {
                situacao = jcbAusente.getText();

            } else if (jcbInativo.isSelected()) {
                situacao = jcbInativo.getText();
            }

            // Verifica se tem campo obrigatório em branco
            if (jtfNome.getText().trim().isEmpty() || jtfSiape.getText().trim().isEmpty()
                    || jtfEmail.getText().trim().isEmpty()
                    || jftfNascimento.getText().equals("  /  /    ")
                    || jftfCelular.getText().equals("(  ) 9     -    ")) {
                JOptionPane.showMessageDialog(null, "Favor preencher todos os campos obrigatórios");

            } else if (jcbNucleo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um núcleo válido");

            } else if (jcbUF.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um estado válido");

            } else if (jcbSexo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Favor selecionar um sexo válido");

            } else {
                mUsuarioEditado.setsNome(jtfNome.getText());
                mUsuarioEditado.setsBairro(jtfBairro.getText());
                mUsuarioEditado.setsCelular(jftfCelular.getText());
                mUsuarioEditado.setsCidade(jtfCidade.getText());
                mUsuarioEditado.setsCpf(jftfCpf.getText());
                mUsuarioEditado.setsDataNascimento(jftfNascimento.getText());
                mUsuarioEditado.setsEmail(jtfEmail.getText());
                mUsuarioEditado.setsEndereco(jtfEndereco.getText());
                mUsuarioEditado.setsInformacoesAdicionais(jtaInformacoesAdicionais.getText());
                mUsuarioEditado.setsNucleo(jcbNucleo.getSelectedItem().toString());
                mUsuarioEditado.setsNumeroCasa(jtfNumeroDaCasa.getText());
                mUsuarioEditado.setsRg(jtfRG.getText());
                mUsuarioEditado.setsSexo(jcbSexo.getSelectedItem().toString());
                mUsuarioEditado.setsSituacao(situacao);
                mUsuarioEditado.setsTelefone(jftfTelefone.getText());
                mUsuarioEditado.setsUf(jcbUF.getSelectedItem().toString());
                mUsuarioEditado.setsSiape(jtfSiape.getText());
                mUsuarioEditado.setiId(mUsuarioLogado.getiId());
                mUsuarioEditado.setbUsuarioAtivo(true);
                System.out.println(mUsuarioEditado.getiId() + " teste");
                if (uDAO.bAlterarUsuarioDAO(mUsuarioEditado)) {
                    JOptionPane.showMessageDialog(null, "Seus dados foram atualizados com sucesso");
                    if (iVeioDeQualTela == 1) {
                        mLogin = c.getmLoginLogado();
                        mLogin.setsSiape(jtfSiape.getText());
                        c.setmUsuarioLogado(mUsuarioEditado);
                        c.setmLoginLogado(mLogin);
                        c.vAbrirTelaPrincipal(6, -1);
                    } else {
                        c.vAbrirTelaPesquisarUsuario(iVeioDeQualTela);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível alterar os seus dados, se o erro persistir consulte o suporte");
                }
            }
        }
    }//GEN-LAST:event_jlbCadastrarOuSalvarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        /* 0 - tPrincipal -> Usuario -> Cadastrar
         * 1 - tPrincipal -> Gerenciar -> redefinir meus dados (editar)  
         * 2 - tPesquisarUsuario -> Editar
         */
        ndao = new NucleoDAO();
        ndao.setControle(c);
        ndao.jComboBoxNucleo(jcbNucleo);
        if (bTeste) {
            if (iVeioDeQualTela == 1 || iVeioDeQualTela == 2) {
                jtfUsuario.setVisible(false);
                jlbUsuario.setVisible(false);
                jpfSenha.setVisible(false);
                jlbSenha.setVisible(false);
                jcbSenhaVisivel.setVisible(false);
                jlbCadastrarOuSalvar.setText("Salvar");
                jtfSiape.setText(mUsuarioLogado.getsSiape());
                jtfNome.setText(mUsuarioLogado.getsNome());
                jtfEndereco.setText(mUsuarioLogado.getsEndereco());
                jtfNumeroDaCasa.setText(mUsuarioLogado.getsNumeroCasa());
                jtfCidade.setText(mUsuarioLogado.getsCidade());
                jtfBairro.setText(mUsuarioLogado.getsBairro());
                if(mUsuarioLogado.getsUf() == null){
                    jcbUF.setSelectedIndex(0);
                } else {
                    jcbUF.setSelectedItem(mUsuarioLogado.getsUf());
                }                
                jftfNascimento.setText(mUsuarioLogado.getsDataNascimento());
                jftfCpf.setText(mUsuarioLogado.getsCpf());
                jtfRG.setText(mUsuarioLogado.getsRg());
                jftfCelular.setText(mUsuarioLogado.getsCelular());
                jftfTelefone.setText(mUsuarioLogado.getsTelefone());
                jcbSexo.setSelectedItem(mUsuarioLogado.getsSexo());
                jtfEmail.setText(mUsuarioLogado.getsEmail());
                jtfSiape.setText(mUsuarioLogado.getsSiape());
                if (mUsuarioLogado.getsSituacao() != null) {
                    switch (mUsuarioLogado.getsSituacao()) {
                        case "Ativo":
                            jcbAtivo.setSelected(true);
                            break;
                        case "Inativo":
                            jcbInativo.setSelected(true);
                            break;
                        default:
                            jcbAusente.setSelected(true);
                            break;
                    }
                }
                jcbNucleo.setSelectedItem(mUsuarioLogado.getsNucleo());
                jtaInformacoesAdicionais.setText(mUsuarioLogado.getsInformacoesAdicionais());
            } else {
                jlbCadastrarOuSalvar.setText("Cadastrar");
            }
            bTeste = false;
        }

    }//GEN-LAST:event_formWindowActivated

    private void jtfSiapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfSiapeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSiapeMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jcbSenhaVisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSenhaVisivelActionPerformed
        // TODO add your handling code here:
        if (jcbSenhaVisivel.isSelected()) {
            jpfSenha.setEchoChar('\u0000');
        } else {
            jpfSenha.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbSenhaVisivelActionPerformed

    public void limparCampos() {
        jtfNome.setText("");
        jtfSiape.setText("");
        jtfEndereco.setText("");
        jtfCidade.setText("");
        jtfBairro.setText("");
        jtfNumeroDaCasa.setText("");
        jcbUF.setSelectedIndex(0);
        jftfNascimento.setText("");
        jtfRG.setText("");
        jftfCpf.setText("");
        jftfCelular.setText("");
        jftfTelefone.setText("");
        jtfEmail.setText("");
        jtaInformacoesAdicionais.setText("");
        jcbAtivo.setSelected(true);
        jcbNucleo.setSelectedIndex(0);
        jcbSexo.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastrarEditarUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCadastrarEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox jcbAtivo;
    private javax.swing.JCheckBox jcbAusente;
    private javax.swing.JCheckBox jcbInativo;
    private javax.swing.JComboBox<String> jcbNucleo;
    private javax.swing.JCheckBox jcbSenhaVisivel;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbUF;
    private javax.swing.JFormattedTextField jftfCelular;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfNascimento;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JLabel jlbCadastrarOuSalvar;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JSeparator jsSeparadorJCB;
    private javax.swing.JTextArea jtaInformacoesAdicionais;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumeroDaCasa;
    private javax.swing.JTextField jtfRG;
    private javax.swing.JTextField jtfSiape;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataDeNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFotoAluno;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumeroDaCasa;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    // End of variables declaration//GEN-END:variables
}
