/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;

/**
 *
 * @author italo
 */
public class TCadastrarEditarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TRealizarConsulta
     */
    public TCadastrarEditarConsulta() {
        initComponents();
    }
    Gerenciamento gRenciamento;

    public void vSetControle(Gerenciamento gGeren) {
        gRenciamento = gGeren;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTextoConsulta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jpInformacoesDaConsulta = new javax.swing.JPanel();
        jlbAluno = new javax.swing.JLabel();
        jlbTurma = new javax.swing.JLabel();
        jlbAtendente = new javax.swing.JLabel();
        jlbSiape = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfSiape = new javax.swing.JTextField();
        jtfAtendente = new javax.swing.JTextField();
        jtfDataInicioConsulta = new javax.swing.JTextField();
        jtfDataTerminoConsulta = new javax.swing.JTextField();
        jtfHoraInicioConsulta = new javax.swing.JTextField();
        jtfHoraTerminoConsulta = new javax.swing.JTextField();
        jtfTituloConsulta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbVisualizarConsulta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbEditarConsulta = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jlbAdiarConsulta = new javax.swing.JLabel();
        jsSeparador1 = new javax.swing.JToolBar.Separator();
        jlbFinalizarConsulta = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfDataEditado = new javax.swing.JTextField();
        jtfHoraEditado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jpConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtaTextoConsulta.setColumns(20);
        jtaTextoConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaTextoConsulta.setLineWrap(true);
        jtaTextoConsulta.setRows(5);
        jtaTextoConsulta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaTextoConsulta);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Texto da consulta:");

        javax.swing.GroupLayout jpConsultaLayout = new javax.swing.GroupLayout(jpConsulta);
        jpConsulta.setLayout(jpConsultaLayout);
        jpConsultaLayout.setHorizontalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpConsultaLayout.setVerticalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_32x32.png")), jpConsulta, ""); // NOI18N

        jlbAluno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbAluno.setText("Aluno:");

        jlbTurma.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbTurma.setText("Matrícula:");

        jlbAtendente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbAtendente.setText("Atendente:");

        jlbSiape.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbSiape.setText("SIAPE:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Início da consulta:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Término da consulta:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Título da consulta:*");

        jtfMatricula.setEditable(false);
        jtfMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfMatricula.setAutoscrolls(false);

        jtfNome.setEditable(false);
        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.setAutoscrolls(false);

        jtfSiape.setEditable(false);
        jtfSiape.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jtfAtendente.setEditable(false);
        jtfAtendente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jtfDataInicioConsulta.setEditable(false);
        jtfDataInicioConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfDataInicioConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataInicioConsulta.setToolTipText("");

        jtfDataTerminoConsulta.setEditable(false);
        jtfDataTerminoConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfDataTerminoConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataTerminoConsulta.setText("Preenchido");
        jtfDataTerminoConsulta.setToolTipText("");

        jtfHoraInicioConsulta.setEditable(false);
        jtfHoraInicioConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfHoraInicioConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfHoraInicioConsulta.setToolTipText("");

        jtfHoraTerminoConsulta.setEditable(false);
        jtfHoraTerminoConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfHoraTerminoConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfHoraTerminoConsulta.setText("automaticamente");
        jtfHoraTerminoConsulta.setToolTipText("");

        jtfTituloConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfTituloConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTituloConsultaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Quem pode visualizar esta consulta?");

        jcbVisualizarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbVisualizarConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o núcleo:", "------------------------", "Todos", "------------------------", "Serviço social", "------------------------", "Pedagogia", "------------------------", "Psicologia", "------------------------", "NAPNE", "------------------------", "Área comum" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Quem pode editar esta consulta?");

        jcbEditarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbEditarConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o núcleo:", "------------------------", "Todos", "------------------------", "Serviço social", "------------------------", "Pedagogia", "------------------------", "Psicologia", "------------------------", "NAPNE", "------------------------", "Área comum" }));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jlbAdiarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbAdiarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Error32x32.png"))); // NOI18N
        jlbAdiarConsulta.setText("Adiar consulta");
        jlbAdiarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAdiarConsultaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlbAdiarConsultaMouseReleased(evt);
            }
        });
        jToolBar1.add(jlbAdiarConsulta);
        jToolBar1.add(jsSeparador1);

        jlbFinalizarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbFinalizarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Accept32x32.png"))); // NOI18N
        jlbFinalizarConsulta.setText("Finalizar consulta");
        jlbFinalizarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbFinalizarConsultaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbFinalizarConsulta);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Última vez editado:");

        jtfDataEditado.setEditable(false);
        jtfDataEditado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfDataEditado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataEditado.setText("Preenchido");
        jtfDataEditado.setToolTipText("");

        jtfHoraEditado.setEditable(false);
        jtfHoraEditado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfHoraEditado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfHoraEditado.setText("automaticamente");
        jtfHoraEditado.setToolTipText("");

        javax.swing.GroupLayout jpInformacoesDaConsultaLayout = new javax.swing.GroupLayout(jpInformacoesDaConsulta);
        jpInformacoesDaConsulta.setLayout(jpInformacoesDaConsultaLayout);
        jpInformacoesDaConsultaLayout.setHorizontalGroup(
            jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbAluno)
                                    .addComponent(jLabel3)
                                    .addComponent(jlbAtendente)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(199, 199, 199))
                            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                .addComponent(jtfDataInicioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jtfHoraInicioConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addGap(68, 68, 68)))
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbTurma)
                            .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                    .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfSiape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jlbSiape)
                                        .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                            .addComponent(jtfDataTerminoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfHoraTerminoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(72, 72, 72)
                                    .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jcbEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jcbVisualizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jtfTituloConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel9)
                    .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                        .addComponent(jtfDataEditado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jtfHoraEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jpInformacoesDaConsultaLayout.setVerticalGroup(
            jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbAluno)
                                    .addComponent(jlbTurma)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpInformacoesDaConsultaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jtfTituloConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbAtendente)
                            .addComponent(jlbSiape))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSiape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDataInicioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDataTerminoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHoraInicioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHoraTerminoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInformacoesDaConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbVisualizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbEditarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInformacoesDaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHoraEditado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informações", new javax.swing.ImageIcon(getClass().getResource("/Icone/Info32x32.png")), jpInformacoesDaConsulta); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public boolean a = true;

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void jlbAdiarConsultaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdiarConsultaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbAdiarConsultaMouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void jlbAdiarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAdiarConsultaMouseClicked

    }//GEN-LAST:event_jlbAdiarConsultaMouseClicked

    private void jlbFinalizarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbFinalizarConsultaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jlbFinalizarConsultaMouseClicked

    private void jtfTituloConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTituloConsultaKeyTyped
        // TODO add your handling code here:
        String numero = evt.getKeyChar() + "";
        if (gRenciamento.bIsLetter(numero)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfTituloConsultaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastrarEditarConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCadastrarEditarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> jcbEditarConsulta;
    private javax.swing.JComboBox<String> jcbVisualizarConsulta;
    private javax.swing.JLabel jlbAdiarConsulta;
    private javax.swing.JLabel jlbAluno;
    private javax.swing.JLabel jlbAtendente;
    private javax.swing.JLabel jlbFinalizarConsulta;
    private javax.swing.JLabel jlbSiape;
    private javax.swing.JLabel jlbTurma;
    private javax.swing.JPanel jpConsulta;
    private javax.swing.JPanel jpInformacoesDaConsulta;
    private javax.swing.JToolBar.Separator jsSeparador1;
    private javax.swing.JTextArea jtaTextoConsulta;
    private javax.swing.JTextField jtfAtendente;
    private javax.swing.JTextField jtfDataEditado;
    private javax.swing.JTextField jtfDataInicioConsulta;
    private javax.swing.JTextField jtfDataTerminoConsulta;
    private javax.swing.JTextField jtfHoraEditado;
    private javax.swing.JTextField jtfHoraInicioConsulta;
    private javax.swing.JTextField jtfHoraTerminoConsulta;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSiape;
    private javax.swing.JTextField jtfTituloConsulta;
    // End of variables declaration//GEN-END:variables
}
