/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.LoginDAO;
import DAO.UsuarioDAO;
import Modelo.MUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class TPesquisarLOGIN extends javax.swing.JFrame {

    /**
     * Creates new form TPesquisarConsulta
     */
    public TPesquisarLOGIN() {
        initComponents();

    }

    Gerenciamento c;
    UsuarioDAO uDAO;
    MUsuario mUsuario;
    LoginDAO ldao;
    int iDeOndeVeio;

    public void setControle(Gerenciamento cp) {
        c = cp;
    }

    public void setTipo(int iTipo) {
        iDeOndeVeio = iTipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOrdenarNome = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jlbPesquisarPor = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtfSiape = new javax.swing.JTextField();
        jlbSiape = new javax.swing.JLabel();
        jtbBotoes = new javax.swing.JToolBar();
        jlbPesquisar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jlbEditarAtendente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jlbRemoverAtendente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDadosAtendente = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jlbSiape1 = new javax.swing.JLabel();
        jcbNucleo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar atendente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlbPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarPor.setText("Pesquisar por:");

        jlbNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNome.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtfSiape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfSiape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSiapeActionPerformed(evt);
            }
        });
        jtfSiape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfSiapeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfSiapeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSiapeKeyTyped(evt);
            }
        });

        jlbSiape.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbSiape.setText("Siape:");

        jtbBotoes.setFloatable(false);
        jtbBotoes.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlbPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Search32x32.png"))); // NOI18N
        jlbPesquisar.setText("Pesquisar");
        jlbPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbPesquisar);
        jtbBotoes.add(jSeparator1);

        jlbEditarAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbEditarAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Edit32x32.png"))); // NOI18N
        jlbEditarAtendente.setText("Editar atendente");
        jlbEditarAtendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEditarAtendenteMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbEditarAtendente);
        jtbBotoes.add(jSeparator2);

        jlbRemoverAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbRemoverAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Trash32x32.png"))); // NOI18N
        jlbRemoverAtendente.setText("Excluir atendente");
        jlbRemoverAtendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbRemoverAtendenteMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbRemoverAtendente);

        jtDadosAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtDadosAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Siape", "Usuário", "Senha", "Acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDadosAtendente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtDadosAtendente.getTableHeader().setReorderingAllowed(false);
        jtDadosAtendente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDadosAtendenteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtDadosAtendente);
        if (jtDadosAtendente.getColumnModel().getColumnCount() > 0) {
            jtDadosAtendente.getColumnModel().getColumn(0).setMinWidth(50);
            jtDadosAtendente.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlbSiape1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbSiape1.setText("Núcleo:");

        jcbNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbNucleo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Serviço social", "Pedagogia", "Psicologia", "NAPNE", "Área comum", "Admin", "Outro" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbPesquisarPor)
                    .addComponent(jtbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNome))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbSiape)
                            .addComponent(jtfSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbSiape1)
                                .addGap(114, 114, 114))
                            .addComponent(jcbNucleo, 0, 166, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbPesquisarPor)
                        .addGap(10, 10, 10)
                        .addComponent(jtbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbSiape)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSiape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbSiape1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased

    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfSiapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSiapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSiapeActionPerformed

    private void jtfSiapeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiapeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfSiapeKeyReleased

    private void jtfSiapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiapeKeyTyped
        // TODO add your handling code here:
        String numero = evt.getKeyChar() + "";
        if (c.bIsNumber(numero)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSiapeKeyTyped

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfSiapeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSiapeKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfSiapeKeyPressed

    private void jlbEditarAtendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditarAtendenteMouseClicked
        // TODO add your handling code here:
        boolean a = false;
        DefaultTableModel tabela = (DefaultTableModel) jtDadosAtendente.getModel();
        uDAO = new UsuarioDAO();
        mUsuario = new MUsuario();
        for (int i = 0; i < jtDadosAtendente.getRowCount(); i++) {
            if (jtDadosAtendente.isRowSelected(i)) {
                a = true;
            }
        }

        if (jtDadosAtendente.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o usuário que deseja editar");

        } else {
            for (int i = 0; i < jtDadosAtendente.getRowCount(); i++) {
                if (jtDadosAtendente.isRowSelected(i)) {
                    a = true;
                }
            }

            if (a) {
                int iLinhaSelecionada = jtDadosAtendente.getSelectedRow(),
                        iId = Integer.parseInt(jtDadosAtendente.getValueAt(iLinhaSelecionada, 0).toString());
                mUsuario = uDAO.muGetUsuarioDAO(iId);
                c.vLimparTabela(tabela);
                c.vAbrirTelaCadastrarEditarUsuario(2, tabela, mUsuario);
            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um atendente antes de editar");
            }
        }
    }//GEN-LAST:event_jlbEditarAtendenteMouseClicked

    private void jlbRemoverAtendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbRemoverAtendenteMouseClicked
        // TODO add your handling code here:
        boolean bAchou = false;
        uDAO = new UsuarioDAO();
        if (jtDadosAtendente.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o atendente que deseja excluir");

        } else {
            for (int i = 0; i < jtDadosAtendente.getRowCount(); i++) {
                if (jtDadosAtendente.isRowSelected(i)) {
                    bAchou = true;
                }
            }
            if (bAchou) {
                int iLinhaSelecionada = jtDadosAtendente.getSelectedRow(), iSeId = Integer.parseInt(jtDadosAtendente.getValueAt(iLinhaSelecionada, 0).toString());
                DefaultTableModel dtmTabela = (DefaultTableModel) jtDadosAtendente.getModel();
                if (uDAO.bRemoverUsuarioDAO(iSeId)) {
                    jlbPesquisarMouseClicked(null);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um atendente antes de excluir");
            }
        }

        /*UsuarioDAO atendente = new UsuarioDAO();
        atendente.removeAll();*/
    }//GEN-LAST:event_jlbRemoverAtendenteMouseClicked

    private void jtDadosAtendenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDadosAtendenteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            jlbRemoverAtendenteMouseClicked(null);
        }
    }//GEN-LAST:event_jtDadosAtendenteKeyPressed

    private void jlbPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtmTabela = (DefaultTableModel) jtDadosAtendente.getModel();
        ldao = new LoginDAO();
        c.vLimparTabela(dtmTabela);
        ldao.vPreencherTabelaPesquisarUsuarioHueHueDAO(dtmTabela);
    }//GEN-LAST:event_jlbPesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPesquisarLOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPesquisarLOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOrdenarNome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcbNucleo;
    private javax.swing.JLabel jlbEditarAtendente;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbPesquisar;
    private javax.swing.JLabel jlbPesquisarPor;
    private javax.swing.JLabel jlbRemoverAtendente;
    private javax.swing.JLabel jlbSiape;
    private javax.swing.JLabel jlbSiape1;
    private javax.swing.JTable jtDadosAtendente;
    private javax.swing.JToolBar jtbBotoes;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfSiape;
    // End of variables declaration//GEN-END:variables
}
