/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import Modelo.MConsulta;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class TPesquisarAlunoConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TPesquisarConsulta
     */
    public TPesquisarAlunoConsulta() {
        initComponents();
    }

    Gerenciamento c;
    String siapeAtendente;
    public void setControle(Gerenciamento cp) {
        c = cp;
    }
    
    public void setSiape(String siape){
        siapeAtendente = siape;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAZNome = new javax.swing.ButtonGroup();
        bgEstadoDaConsulta = new javax.swing.ButtonGroup();
        bgAZTituloDaConsulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDadosConsulta = new javax.swing.JTable();
        jtfMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlbPesquisarPor = new javax.swing.JLabel();
        jToolBar4 = new javax.swing.JToolBar();
        jlbPesquisarAluno = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jlbNovaConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Aluno para Consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jtDadosConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtDadosConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matrícula", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDadosConsulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtDadosConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtDadosConsulta);

        jtfMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMatriculaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMatriculaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Matrícula");

        jlbPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbPesquisarPor.setText("Pesquisar por:");

        jToolBar4.setFloatable(false);
        jToolBar4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar4.setRollover(true);

        jlbPesquisarAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Search32x32.png"))); // NOI18N
        jlbPesquisarAluno.setText("Pesquisar aluno");
        jlbPesquisarAluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlbPesquisarAlunoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jlbPesquisarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarAlunoMouseClicked(evt);
            }
        });
        jToolBar4.add(jlbPesquisarAluno);
        jToolBar4.add(jSeparator3);

        jlbNovaConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNovaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Add32x32.png"))); // NOI18N
        jlbNovaConsulta.setText("Nova consulta");
        jlbNovaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNovaConsultaMouseClicked(evt);
            }
        });
        jToolBar4.add(jlbNovaConsulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPesquisarPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbPesquisarPor)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)
                                .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //c.fecharTelaPesquisarAlunoConsulta();
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // TODO add your handling code here
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        // TODO add your handling code here:
        /*String situacao = "";
        String nome = jtfNome.getText();
        String matricula = jtfMatricula.getText();
        String curso = jcbCurso.getSelectedItem().toString();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();*/

    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMatriculaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMatriculaKeyReleased

    private void jtfMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMatriculaKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfMatriculaKeyTyped

    private void jlbPesquisarAlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlbPesquisarAlunoAncestorAdded
        // TODO add your handling code here:

        /*String nome = jtfNome.getText(), matricula = jtfMatricula.getText(), curso = jcbCurso.getSelectedItem().toString();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        if (curso.equals("Selecione um curso:") || curso.equals("----------------------")) {
            JOptionPane.showMessageDialog(this, "Selecione um curso válido");

        } else {
            //c.preencherTabelaPesquisaConsulta(tabela, nome, matricula, curso);
        }*/

    }//GEN-LAST:event_jlbPesquisarAlunoAncestorAdded

    private void jlbNovaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNovaConsultaMouseClicked
        // TODO add your handling code here:
        boolean a = false;
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        if (jtDadosConsulta.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar um aluno antes de fazer a consulta");

        } else {
            for (int i = 0; i < jtDadosConsulta.getRowCount(); i++) {
                if (jtDadosConsulta.isRowSelected(i)) {
                    a = true;
                }
            }
            if (a) {
                int linha = jtDadosConsulta.getSelectedRow(), coluna = 1, tipoCadastrarOuEditar = 0;
                String matricula = jtDadosConsulta.getValueAt(linha, coluna).toString();
                MConsulta con = null;
//                c.vAbrirTelaCadastrarEditarConsulta(con, matricula, siapeAtendente, tipoCadastrarOuEditar, tabela);

            } else {
                JOptionPane.showMessageDialog(null, "Um aluno precisa ser selecionado para realizar a consulta");
            }
        }
    }//GEN-LAST:event_jlbNovaConsultaMouseClicked

    private void jlbPesquisarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarAlunoMouseClicked
        // TODO add your handling code here:
       /* String nome = jtfNome.getText(), matricula = jtfMatricula.getText(), curso = jcbCurso.getSelectedItem().toString();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();

        if (curso.equals("Selecione o curso:") || curso.equals("----------------------")) {
            JOptionPane.showMessageDialog(this, "Selecione um curso válido");

        } else {
            c.preencherTabelaPesquisaAluno(tabela, nome, matricula, curso);
        }*/
    }//GEN-LAST:event_jlbPesquisarAlunoMouseClicked

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPesquisarAlunoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPesquisarAlunoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAZNome;
    private javax.swing.ButtonGroup bgAZTituloDaConsulta;
    private javax.swing.ButtonGroup bgEstadoDaConsulta;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JLabel jlbNovaConsulta;
    private javax.swing.JLabel jlbPesquisarAluno;
    private javax.swing.JLabel jlbPesquisarPor;
    private javax.swing.JTable jtDadosConsulta;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
