/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.NucleoDAO;
import DAO.UsuarioDAO;
import Modelo.MNucleo;
import Modelo.MUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class TPesquisarNucleo extends javax.swing.JFrame {

    /**
     * Creates new form TPesquisarConsulta
     */
    public TPesquisarNucleo() {
        initComponents();

    }

    Gerenciamento c;
    UsuarioDAO uDAO;
    MUsuario mUsuario;
    MNucleo mNucleo;
    NucleoDAO ndao;
    int iDeOndeVeio;

    public void setControle(Gerenciamento cp) {
        c = cp;
    }

    public void setTipo(int iTipo) {
        iDeOndeVeio = iTipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOrdenarNome = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jlbPesquisarPor = new javax.swing.JLabel();
        jlbNomeNucleo = new javax.swing.JLabel();
        jtfNomeNucleo = new javax.swing.JTextField();
        jtbBotoes = new javax.swing.JToolBar();
        jlbPesquisarNucleo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jlbEditarNucleo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jlbRemoverNucleo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDadosNucleo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar atendente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlbPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarPor.setText("Pesquisar por:");

        jlbNomeNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNomeNucleo.setText("Nome:");

        jtfNomeNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNomeNucleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeNucleoActionPerformed(evt);
            }
        });
        jtfNomeNucleo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeNucleoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeNucleoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeNucleoKeyTyped(evt);
            }
        });

        jtbBotoes.setFloatable(false);
        jtbBotoes.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlbPesquisarNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarNucleo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPesquisarNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Search32x32.png"))); // NOI18N
        jlbPesquisarNucleo.setText("Pesquisar");
        jlbPesquisarNucleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarNucleoMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbPesquisarNucleo);
        jtbBotoes.add(jSeparator1);

        jlbEditarNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbEditarNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Edit32x32.png"))); // NOI18N
        jlbEditarNucleo.setText("Editar núcleo");
        jlbEditarNucleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEditarNucleoMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbEditarNucleo);
        jtbBotoes.add(jSeparator2);

        jlbRemoverNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbRemoverNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/user/User_Trash32x32.png"))); // NOI18N
        jlbRemoverNucleo.setText("Excluir núcleo");
        jlbRemoverNucleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbRemoverNucleoMouseClicked(evt);
            }
        });
        jtbBotoes.add(jlbRemoverNucleo);

        jtDadosNucleo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtDadosNucleo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Permissoes de aceso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDadosNucleo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtDadosNucleo.getTableHeader().setReorderingAllowed(false);
        jtDadosNucleo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDadosNucleoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtDadosNucleo);
        if (jtDadosNucleo.getColumnModel().getColumnCount() > 0) {
            jtDadosNucleo.getColumnModel().getColumn(0).setMinWidth(50);
            jtDadosNucleo.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbPesquisarPor)
                    .addComponent(jtbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNomeNucleo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbPesquisarPor)
                        .addGap(10, 10, 10)
                        .addComponent(jtbBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbNomeNucleo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeNucleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(iDeOndeVeio == 0){
            c.vAbrirTelaPrincipal(8, -1);
        } else if (iDeOndeVeio == 1){
            c.vAbrirTelaCadastrarEditarNucleo(1);
        }            
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeNucleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeNucleoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeNucleoActionPerformed

    private void jtfNomeNucleoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeNucleoKeyReleased

    }//GEN-LAST:event_jtfNomeNucleoKeyReleased

    private void jtfNomeNucleoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeNucleoKeyTyped
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeNucleoKeyTyped

    private void jtfNomeNucleoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeNucleoKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfNomeNucleoKeyPressed

    private void jlbEditarNucleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditarNucleoMouseClicked
        // TODO add your handling code here:
        boolean a = false;
        DefaultTableModel tabela = (DefaultTableModel) jtDadosNucleo.getModel();
        uDAO = new UsuarioDAO();
        mUsuario = new MUsuario();
        for (int i = 0; i < jtDadosNucleo.getRowCount(); i++) {
            if (jtDadosNucleo.isRowSelected(i)) {
                a = true;
            }
        }

        if (jtDadosNucleo.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o usuário que deseja editar");

        } else {
            for (int i = 0; i < jtDadosNucleo.getRowCount(); i++) {
                if (jtDadosNucleo.isRowSelected(i)) {
                    a = true;
                }
            }

            if (a) {
                int iLinhaSelecionada = jtDadosNucleo.getSelectedRow(),
                        iId = Integer.parseInt(jtDadosNucleo.getValueAt(iLinhaSelecionada, 0).toString());
                mUsuario = uDAO.muGetUsuarioDAO(iId);
                c.vLimparTabela(tabela);
                c.vAbrirTelaCadastrarEditarUsuario(2, tabela, mUsuario);
            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um atendente antes de editar");
            }
        }
    }//GEN-LAST:event_jlbEditarNucleoMouseClicked

    private void jlbRemoverNucleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbRemoverNucleoMouseClicked
        // TODO add your handling code here:
        boolean bAchou = false;
        uDAO = new UsuarioDAO();
        if (jtDadosNucleo.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o atendente que deseja excluir");

        } else {
            for (int i = 0; i < jtDadosNucleo.getRowCount(); i++) {
                if (jtDadosNucleo.isRowSelected(i)) {
                    bAchou = true;
                }
            }
            if (bAchou) {
                int iLinhaSelecionada = jtDadosNucleo.getSelectedRow(), iSeId = Integer.parseInt(jtDadosNucleo.getValueAt(iLinhaSelecionada, 0).toString());
                DefaultTableModel dtmTabela = (DefaultTableModel) jtDadosNucleo.getModel();
                if (uDAO.bRemoverUsuarioDAO(iSeId)) {
                }

            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um atendente antes de excluir");
            }
        }

        /*UsuarioDAO atendente = new UsuarioDAO();
        atendente.removeAll();*/
    }//GEN-LAST:event_jlbRemoverNucleoMouseClicked

    private void jtDadosNucleoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDadosNucleoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
        }
    }//GEN-LAST:event_jtDadosNucleoKeyPressed

    private void jlbPesquisarNucleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarNucleoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtmTabela = (DefaultTableModel) jtDadosNucleo.getModel();
        String sNomeNucleo = jtfNomeNucleo.getText();
        c.vLimparTabela(dtmTabela);
        ndao = new NucleoDAO();
        ndao.vPreencherTabelaPesquisarNucleoDAO(dtmTabela, sNomeNucleo);
    }//GEN-LAST:event_jlbPesquisarNucleoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPesquisarNucleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPesquisarNucleo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOrdenarNome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JLabel jlbEditarNucleo;
    private javax.swing.JLabel jlbNomeNucleo;
    private javax.swing.JLabel jlbPesquisarNucleo;
    private javax.swing.JLabel jlbPesquisarPor;
    private javax.swing.JLabel jlbRemoverNucleo;
    private javax.swing.JTable jtDadosNucleo;
    private javax.swing.JToolBar jtbBotoes;
    private javax.swing.JTextField jtfNomeNucleo;
    // End of variables declaration//GEN-END:variables
}
