/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.UsuarioDAO;
import com.itextpdf.text.BadElementException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeDebug;

/**
 *
 * @author italo
 */
public class TPesquisarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TPesquisarConsulta
     */
    public TPesquisarConsulta() {
        initComponents();
    }

    Gerenciamento c;

    public void setControle(Gerenciamento cp) {
        c = cp;
    }

    int nucleoLogado;
    String nomeAtendente;
    String siapeAtendente;

    public void setAtendenteLogado(int nucleologado, String nome) {
        nucleoLogado = nucleologado;
        nomeAtendente = nome;
    }

    public void setSiape(String siape) {
        siapeAtendente = siape;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAZNome = new javax.swing.ButtonGroup();
        bgEstadoDaConsulta = new javax.swing.ButtonGroup();
        bgAZTituloDaConsulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDadosConsulta = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtfTituloDaConsulta = new javax.swing.JTextField();
        jtfMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToolBar5 = new javax.swing.JToolBar();
        jlbPesquisarPor = new javax.swing.JLabel();
        jToolBar4 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        jlbPesquisarNome = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jlbPesquisarMatricula = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jlbPesquisarTituloDaConsulta = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jlbEditarConsulta = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jlbExcluirConsulta = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jlbGerarConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jtDadosConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtDadosConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matrícula", "Título da consulta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDadosConsulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtDadosConsulta.getTableHeader().setReorderingAllowed(false);
        jtDadosConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDadosConsultaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtDadosConsulta);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Título da consulta:");

        jtfTituloDaConsulta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfTituloDaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTituloDaConsultaActionPerformed(evt);
            }
        });
        jtfTituloDaConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTituloDaConsultaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTituloDaConsultaKeyTyped(evt);
            }
        });

        jtfMatricula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMatriculaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMatriculaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Matrícula");

        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        jlbPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbPesquisarPor.setText("Pesquisar por:");

        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jlbPesquisarNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Search32x32.png"))); // NOI18N
        jlbPesquisarNome.setText("Pesquisa por nome");
        jlbPesquisarNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarNomeMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbPesquisarNome);
        jToolBar1.add(jSeparator3);

        jlbPesquisarMatricula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Search32x32.png"))); // NOI18N
        jlbPesquisarMatricula.setText("Pesquisa por matrícula");
        jlbPesquisarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarMatriculaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbPesquisarMatricula);
        jToolBar1.add(jSeparator4);

        jlbPesquisarTituloDaConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbPesquisarTituloDaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Search32x32.png"))); // NOI18N
        jlbPesquisarTituloDaConsulta.setText("Pesquisa por título da consulta");
        jlbPesquisarTituloDaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPesquisarTituloDaConsultaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbPesquisarTituloDaConsulta);
        jToolBar1.add(jSeparator8);

        jlbEditarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbEditarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Edit32x32.png"))); // NOI18N
        jlbEditarConsulta.setText("Editar consulta");
        jlbEditarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEditarConsultaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbEditarConsulta);
        jToolBar1.add(jSeparator5);

        jlbExcluirConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbExcluirConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Trash32x32.png"))); // NOI18N
        jlbExcluirConsulta.setText("Excluir consulta");
        jlbExcluirConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExcluirConsultaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbExcluirConsulta);
        jToolBar1.add(jSeparator6);

        jlbGerarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbGerarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/note/Note_Print32x32.png"))); // NOI18N
        jlbGerarConsulta.setText("Gerar relatorio");
        jlbGerarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbGerarConsultaMouseClicked(evt);
            }
        });
        jToolBar1.add(jlbGerarConsulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbPesquisarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jtfTituloDaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPesquisarPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTituloDaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        c.vAbrirTelaPrincipal(3, -1);
    }//GEN-LAST:event_formWindowClosing

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // TODO add your handling code here
        String letra = evt.getKeyChar() + "";
        if (c.bIsLetter(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlbPesquisarNomeMouseClicked(null);
        }
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jtfMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMatriculaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlbPesquisarMatriculaMouseClicked(null);
        }
    }//GEN-LAST:event_jtfMatriculaKeyReleased

    private void jtfMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMatriculaKeyTyped
        // TODO add your handling code here:
        String letra = evt.getKeyChar() + "";
        if (c.bIsNumber(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfMatriculaKeyTyped

    private void jlbPesquisarNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarNomeMouseClicked
        // TODO add your handling code here:
        String nome = jtfNome.getText();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        c.vLimparTabela(tabela);
        //ConsultaDAO consultaDAO = new ConsultaDAO();
        //consultaDAO.preencherTabelaPesquisaConsulta(0, tabela, nome, "", "");

    }//GEN-LAST:event_jlbPesquisarNomeMouseClicked

    private void jlbExcluirConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExcluirConsultaMouseClicked
        // TODO add your handling code here:
        String nome = jtfNome.getText();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        int linha = jtDadosConsulta.getSelectedRow();
        String tituloDaConsulta = (String) tabela.getValueAt(linha, 2);
       // ConsultaDAO consultaDAO = new ConsultaDAO();
       // consultaDAO.removerConsulta(tabela, nome, tituloDaConsulta);
        c.vLimparTabela(tabela);
       // consultaDAO.preencherTabelaPesquisaConsulta(1, tabela, "", "", "");
    }//GEN-LAST:event_jlbExcluirConsultaMouseClicked

    private void jtDadosConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDadosConsultaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            jlbExcluirConsultaMouseClicked(null);
        }
    }//GEN-LAST:event_jtDadosConsultaKeyPressed

    private void jlbGerarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbGerarConsultaMouseClicked
        // TODO add your handling code here:
        /*boolean a = false;
        if (jtDadosConsulta.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o aluno que deseja alterar a consulta");

        } else {
            for (int i = 0; i < jtDadosConsulta.getRowCount(); i++) {
                if (jtDadosConsulta.isRowSelected(i)) {
                    a = true;
                }
            }

            if (a) {
                int linha = jtDadosConsulta.getSelectedRow(), colunaMatricula = 1, colunaNome = 0;
                String matricula = jtDadosConsulta.getValueAt(linha, colunaMatricula).toString();
                String nome = jtDadosConsulta.getValueAt(linha, colunaNome).toString();
                try {
                    c.vRelatorioConsulta(matricula, nome);
                } catch (IOException | BadElementException ex) {
                    System.out.println(ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um aluno antes");
            }
        }*/
        JOptionPane.showMessageDialog(null, "Disponível em versões futuras. (bem futuras huehuehuehue)");
    }//GEN-LAST:event_jlbGerarConsultaMouseClicked

    private void jlbEditarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditarConsultaMouseClicked
        // TODO add your handling code here:
        boolean a = false;
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        if (jtDadosConsulta.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Faça uma pesquisa para selecionar o aluno que deseja editar");

        } else {
            for (int i = 0; i < jtDadosConsulta.getRowCount(); i++) {
                if (jtDadosConsulta.isRowSelected(i)) {
                    a = true;
                }
            }

            if (a) { // editar == 1 cadastrar == 0
                int linha = jtDadosConsulta.getSelectedRow(), colunaMatricula = 1, tipoCadastrarOuEditar = 1, colunaTitulo = 2;
                String matricula = jtDadosConsulta.getValueAt(linha, colunaMatricula).toString(),
                        tituloDaConsulta = jtDadosConsulta.getValueAt(linha, colunaTitulo).toString();

                //jlbPesquisarConsultaMouseClicked(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Favor selecionar um aluno antes de editar");
            }
        }
    }//GEN-LAST:event_jlbEditarConsultaMouseClicked

    private void jtfTituloDaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTituloDaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTituloDaConsultaActionPerformed

    private void jlbPesquisarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarMatriculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbPesquisarMatriculaMouseClicked

    private void jlbPesquisarTituloDaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPesquisarTituloDaConsultaMouseClicked
        // TODO add your handling code here:
        String tituloDaConsulta = jtfTituloDaConsulta.getText();
        DefaultTableModel tabela = (DefaultTableModel) jtDadosConsulta.getModel();
        c.vLimparTabela(tabela);
       // ConsultaDAO consultaDAO = new ConsultaDAO();
      //  consultaDAO.preencherTabelaPesquisaConsulta(2, tabela, "", "", tituloDaConsulta);
    }//GEN-LAST:event_jlbPesquisarTituloDaConsultaMouseClicked

    private void jtfTituloDaConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTituloDaConsultaKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlbPesquisarTituloDaConsultaMouseClicked(null);
        }
    }//GEN-LAST:event_jtfTituloDaConsultaKeyReleased

    private void jtfTituloDaConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTituloDaConsultaKeyTyped
        // TODO add your handling code here:
        String numero = evt.getKeyChar() + "";
        if (c.bIsLetter(numero)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfTituloDaConsultaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPesquisarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPesquisarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPesquisarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPesquisarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPesquisarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAZNome;
    private javax.swing.ButtonGroup bgAZTituloDaConsulta;
    private javax.swing.ButtonGroup bgEstadoDaConsulta;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JLabel jlbEditarConsulta;
    private javax.swing.JLabel jlbExcluirConsulta;
    private javax.swing.JLabel jlbGerarConsulta;
    private javax.swing.JLabel jlbPesquisarMatricula;
    private javax.swing.JLabel jlbPesquisarNome;
    private javax.swing.JLabel jlbPesquisarPor;
    private javax.swing.JLabel jlbPesquisarTituloDaConsulta;
    private javax.swing.JTable jtDadosConsulta;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTituloDaConsulta;
    // End of variables declaration//GEN-END:variables
}
