/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.NucleoDAO;
import DAO.UsuarioDAO;
import Modelo.MAluno;
import Modelo.MLogin;
import Modelo.MUsuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ítalo
 */
public class TPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public TPrincipal() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension Dimencao = tk.getScreenSize();
        int Daltura = Dimencao.height, Dlargura = Dimencao.width;
        Daltura = (Daltura / 3) * 2;
        Dlargura = (int) (Daltura * 1.618033988749895); // Fibonacci
        this.setSize(Dlargura, Daltura);
        jLista.setModel(new DefaultListModel());
    }

    Gerenciamento c;
    DefaultTableModel dtmTabela;
    MLogin mLogin;
    MUsuario mUsuario;
    UsuarioDAO uDAO;

    public void setControle(Gerenciamento cp) {
        c = cp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCoisas = new javax.swing.JButton();
        jcbTeste = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUCadastrar = new javax.swing.JMenuItem();
        jmiUPesquisar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiGPersonalizar = new javax.swing.JMenuItem();
        jmiGDadosPessoais = new javax.swing.JMenu();
        jmiGRedefinirLogin = new javax.swing.JMenuItem();
        jmiGRedefinirMeusDados = new javax.swing.JMenuItem();
        jmiGSair = new javax.swing.JMenuItem();
        jmiGEncerrarSistema = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiNCadastrar = new javax.swing.JMenuItem();
        jmiNPesquisar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setFocusTraversalPolicyProvider(true);
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(618, 1066));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCoisas.setText("Teste de coisas");
        btnCoisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoisasActionPerformed(evt);
            }
        });

        jcbTeste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        jLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jLista);

        jButton1.setText("Preencher tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCoisas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoisas))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jMenu1.setText("Usuário");

        jmiUCadastrar.setText("Cadastrar");
        jmiUCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUCadastrar);

        jmiUPesquisar.setText("Pesquisar");
        jmiUPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUPesquisarActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUPesquisar);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Gerenciar");

        jmiGPersonalizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jmiGPersonalizar.setText("Personalizar");
        jmiGPersonalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGPersonalizarActionPerformed(evt);
            }
        });
        jMenu3.add(jmiGPersonalizar);

        jmiGDadosPessoais.setText("Dados pessoais");

        jmiGRedefinirLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiGRedefinirLogin.setText("Redefinir login");
        jmiGRedefinirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGRedefinirLoginActionPerformed(evt);
            }
        });
        jmiGDadosPessoais.add(jmiGRedefinirLogin);

        jmiGRedefinirMeusDados.setText("Redefinir meus dados");
        jmiGRedefinirMeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGRedefinirMeusDadosActionPerformed(evt);
            }
        });
        jmiGDadosPessoais.add(jmiGRedefinirMeusDados);

        jMenu3.add(jmiGDadosPessoais);

        jmiGSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiGSair.setText("Sair");
        jmiGSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGSairActionPerformed(evt);
            }
        });
        jMenu3.add(jmiGSair);

        jmiGEncerrarSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jmiGEncerrarSistema.setText("Encerrar sistema");
        jmiGEncerrarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGEncerrarSistemaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiGEncerrarSistema);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Núcleo");

        jmiNCadastrar.setText("Cadastrar");
        jmiNCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNCadastrar);

        jmiNPesquisar.setText("Pesquisar");
        jmiNPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNPesquisar);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Hue Hue");

        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here: 
        c.vEncerrarSistema();
    }//GEN-LAST:event_formWindowClosing

    private void btnCoisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoisasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoisasActionPerformed

    private void jmiGPersonalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGPersonalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiGPersonalizarActionPerformed

    private void jmiGSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGSairActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaLogin(1);
    }//GEN-LAST:event_jmiGSairActionPerformed

    private void jmiGRedefinirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGRedefinirLoginActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaRedefinirLogin();
    }//GEN-LAST:event_jmiGRedefinirLoginActionPerformed

    private void jmiGRedefinirMeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGRedefinirMeusDadosActionPerformed
        // TODO add your handling code here:
        dtmTabela = new DefaultTableModel();
        mUsuario = new MUsuario();
        uDAO = new UsuarioDAO();
        mUsuario = uDAO.muGetUsuarioDAO(c.getmLoginLogado().getiId());
        c.vAbrirTelaCadastrarEditarUsuario(1, dtmTabela, mUsuario);
    }//GEN-LAST:event_jmiGRedefinirMeusDadosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void jmiGEncerrarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGEncerrarSistemaActionPerformed
        // TODO add your handling code here:
        c.vEncerrarSistema();
    }//GEN-LAST:event_jmiGEncerrarSistemaActionPerformed

    private void jmiUCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUCadastrarActionPerformed
        // TODO add your handling code here:
        mUsuario = new MUsuario();
        String sNucleoLogado = c.getmUsuarioLogado().getsNucleo();
        if (sNucleoLogado.equals("Área comum")) {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para acessar esta aba");
        } else {
            c.vAbrirTelaCadastrarEditarUsuario(0, dtmTabela, mUsuario);
        }
    }//GEN-LAST:event_jmiUCadastrarActionPerformed

    private void jmiUPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUPesquisarActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaPesquisarUsuario(0);
    }//GEN-LAST:event_jmiUPesquisarActionPerformed

    private void jmiNCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNCadastrarActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaCadastrarEditarNucleo(0);
    }//GEN-LAST:event_jmiNCadastrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaPesquisarLOGIN();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiNPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNPesquisarActionPerformed
        // TODO add your handling code here:
        c.vAbrirTelaPesquisarNucleo();
    }//GEN-LAST:event_jmiNPesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        c.vAdicionarLinhaTabela((DefaultTableModel) jtTabela.getModel());
        
        c.vAdicionarAPorraDoElemento((DefaultListModel) jLista.getModel());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoisas;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jLista;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbTeste;
    private javax.swing.JMenu jmiGDadosPessoais;
    private javax.swing.JMenuItem jmiGEncerrarSistema;
    private javax.swing.JMenuItem jmiGPersonalizar;
    private javax.swing.JMenuItem jmiGRedefinirLogin;
    private javax.swing.JMenuItem jmiGRedefinirMeusDados;
    private javax.swing.JMenuItem jmiGSair;
    private javax.swing.JMenuItem jmiNCadastrar;
    private javax.swing.JMenuItem jmiNPesquisar;
    private javax.swing.JMenuItem jmiUCadastrar;
    private javax.swing.JMenuItem jmiUPesquisar;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables

}
