/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Gerenciamento;
import DAO.LoginDAO;
import Modelo.MLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class TRedefinirLogin extends javax.swing.JFrame {

    /**
     * Creates new form TRedefinirLogin
     */
    public TRedefinirLogin() {
        initComponents();
    }

    Gerenciamento c;
    MLogin mLoginUsuarioLogado;
    LoginDAO lDAO;
    boolean bInserirOsDadosNaTela = true;

    public void setControle(Gerenciamento cg) {
        c = cg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlbSenhaAntiga = new javax.swing.JLabel();
        jcbSenhaAntiga = new javax.swing.JCheckBox();
        jpfSenhaAntiga = new javax.swing.JPasswordField();
        jlbRedefinir = new javax.swing.JLabel();
        jlbCancelar = new javax.swing.JLabel();
        jlbNovaSenha = new javax.swing.JLabel();
        jpfNovaSenha = new javax.swing.JPasswordField();
        jcbNovaSenha = new javax.swing.JCheckBox();
        jlbNovaSenhaConfirmar = new javax.swing.JLabel();
        jpfConfirmarSenhaNova = new javax.swing.JPasswordField();
        jcbConfirmarNovaSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Usuário: ");

        jtfUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlbSenhaAntiga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbSenhaAntiga.setText("Senha antiga: ");

        jcbSenhaAntiga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbSenhaAntigaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbSenhaAntigaFocusLost(evt);
            }
        });
        jcbSenhaAntiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSenhaAntigaActionPerformed(evt);
            }
        });

        jpfSenhaAntiga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlbRedefinir.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbRedefinir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Edit32x32.png"))); // NOI18N
        jlbRedefinir.setText("Redefinir");
        jlbRedefinir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbRedefinirMouseClicked(evt);
            }
        });

        jlbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Deny32x32.png"))); // NOI18N
        jlbCancelar.setText("Cancelar");
        jlbCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCancelarMouseClicked(evt);
            }
        });
        jlbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlbCancelarKeyPressed(evt);
            }
        });

        jlbNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNovaSenha.setText("Nova senha:");

        jpfNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcbNovaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbNovaSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbNovaSenhaFocusLost(evt);
            }
        });
        jcbNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNovaSenhaActionPerformed(evt);
            }
        });

        jlbNovaSenhaConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlbNovaSenhaConfirmar.setText("Confirme sua nova senha:");

        jpfConfirmarSenhaNova.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcbConfirmarNovaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbConfirmarNovaSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbConfirmarNovaSenhaFocusLost(evt);
            }
        });
        jcbConfirmarNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConfirmarNovaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNovaSenhaConfirmar)
                    .addComponent(jLabel1)
                    .addComponent(jlbSenhaAntiga)
                    .addComponent(jlbNovaSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpfNovaSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfSenhaAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jpfConfirmarSenhaNova))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbConfirmarNovaSenha)
                            .addComponent(jcbSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNovaSenha))))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jlbRedefinir)
                .addGap(18, 18, 18)
                .addComponent(jlbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpfSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbSenhaAntiga))
                            .addComponent(jcbSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jpfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbNovaSenha))
                            .addComponent(jcbNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbNovaSenhaConfirmar)
                        .addComponent(jpfConfirmarSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbConfirmarNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRedefinir)
                    .addComponent(jlbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbSenhaAntigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSenhaAntigaActionPerformed
        // TODO add your handling code here:
        if (jcbSenhaAntiga.isSelected()) {
            jpfSenhaAntiga.setEchoChar('\u0000');
        } else {
            jpfSenhaAntiga.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbSenhaAntigaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        c.vAbrirTelaPrincipal(4, -1);
    }//GEN-LAST:event_formWindowClosing

    private void jcbSenhaAntigaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbSenhaAntigaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSenhaAntigaFocusGained

    private void jcbSenhaAntigaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbSenhaAntigaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSenhaAntigaFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (bInserirOsDadosNaTela) {
            bInserirOsDadosNaTela = false;
            mLoginUsuarioLogado = new MLogin();
            mLoginUsuarioLogado = c.getmLoginLogado();
            jtfUsuario.setText(mLoginUsuarioLogado.getsUsuario());
        }
    }//GEN-LAST:event_formWindowActivated

    private void jlbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlbCancelarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jlbCancelarKeyPressed

    private void jlbCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCancelarMouseClicked
        // TODO add your handling code here:
        c.vAbrirTelaPrincipal(4, -1);
    }//GEN-LAST:event_jlbCancelarMouseClicked

    private void jlbRedefinirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbRedefinirMouseClicked
        // TODO add your handling code here:
        String sUsuarioDigitado = jtfUsuario.getText(),
                sSenhaAntiga = jpfSenhaAntiga.getText(),
                sNovaSenha = jpfNovaSenha.getText(),
                sConfirmaSenha = jpfConfirmarSenhaNova.getText();
        lDAO = new LoginDAO();
        mLoginUsuarioLogado = new MLogin();
        if (sSenhaAntiga.trim().isEmpty() || sNovaSenha.trim().isEmpty() || sConfirmaSenha.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode ficar em branco!");
        } else if (sUsuarioDigitado.equals(c.getmLoginLogado().getsUsuario()) || !lDAO.bValidarLoginExistente(sUsuarioDigitado)) {
            if (sSenhaAntiga.equals(c.getmLoginLogado().getsSenha())) {
                if (sNovaSenha.equals(sConfirmaSenha)) {
                    mLoginUsuarioLogado = c.getmLoginLogado();
                    mLoginUsuarioLogado.setsSenha(sNovaSenha);
                    mLoginUsuarioLogado.setsUsuario(sUsuarioDigitado);
                    if (lDAO.bAlterarLogin(3, mLoginUsuarioLogado, "")) {
                        JOptionPane.showMessageDialog(null, "Login alterado com sucesso");
                        c.vAbrirTelaPrincipal(4, -1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Não foi possível alterar o login, caso o erro persista informe ao suporte");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "As senhas não conferem");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha antiga inválida");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Já existe um login no sistema com esse mesmo usuário, favor informar outro");
        }
    }//GEN-LAST:event_jlbRedefinirMouseClicked

    private void jcbNovaSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbNovaSenhaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNovaSenhaFocusGained

    private void jcbNovaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbNovaSenhaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNovaSenhaFocusLost

    private void jcbNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNovaSenhaActionPerformed
        // TODO add your handling code here:
        if (jcbNovaSenha.isSelected()) {
            jpfNovaSenha.setEchoChar('\u0000');
        } else {
            jpfNovaSenha.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbNovaSenhaActionPerformed

    private void jcbConfirmarNovaSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbConfirmarNovaSenhaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbConfirmarNovaSenhaFocusGained

    private void jcbConfirmarNovaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbConfirmarNovaSenhaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbConfirmarNovaSenhaFocusLost

    private void jcbConfirmarNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConfirmarNovaSenhaActionPerformed
        // TODO add your handling code here:
        if (jcbConfirmarNovaSenha.isSelected()) {
            jpfConfirmarSenhaNova.setEchoChar('\u0000');
        } else {
            jpfConfirmarSenhaNova.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jcbConfirmarNovaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRedefinirLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRedefinirLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRedefinirLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRedefinirLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRedefinirLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbConfirmarNovaSenha;
    private javax.swing.JCheckBox jcbNovaSenha;
    private javax.swing.JCheckBox jcbSenhaAntiga;
    private javax.swing.JLabel jlbCancelar;
    private javax.swing.JLabel jlbNovaSenha;
    private javax.swing.JLabel jlbNovaSenhaConfirmar;
    private javax.swing.JLabel jlbRedefinir;
    private javax.swing.JLabel jlbSenhaAntiga;
    private javax.swing.JPasswordField jpfConfirmarSenhaNova;
    private javax.swing.JPasswordField jpfNovaSenha;
    private javax.swing.JPasswordField jpfSenhaAntiga;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
